spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=20000
spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret = 4kKFr50fKtksgs8/4iZPfK4kNiqH7k8NrzkHujP8K/Q=
app.admin.username = admin-test
app.admin.password = test4321
